alter table if exists inventory
  add column if not exists purchase_length_meters numeric,
  add column if not exists purchase_length numeric,
  add column if not exists buy_length_meters numeric,
  add column if not exists length_meters numeric,
  add column if not exists standard_size numeric,
  add column if not exists photo_url text,
  add column if not exists image_url text,
  add column if not exists photo text,
  add column if not exists image text,
  add column if not exists photo_bucket text,
  add column if not exists image_bucket text,
  add column if not exists storage_bucket text,
  add column if not exists photo_path text,
  add column if not exists image_path text,
  add column if not exists path text;

alter table if exists products
  add column if not exists image text,
  add column if not exists composition jsonb,
  add column if not exists productCategory text,
  add column if not exists productType text,
  add column if not exists productSubCategory1 text,
  add column if not exists productSubCategory2 text,
  add column if not exists desiredProfitMargin numeric,
  add column if not exists laborCost numeric,
  add column if not exists productionHours numeric,
  add column if not exists assemblyHours numeric,
  add column if not exists hourlyRate numeric,
  add column if not exists fixedCostRate numeric,
  add column if not exists absorptionRate numeric,
  add column if not exists quantityReference integer,
  add column if not exists selectedCategoryColor text,
  add column if not exists referenceWidthMm integer,
  add column if not exists referenceHeightMm integer;
